site_name: Brasil Channel

nav:
    - Inicio: 'index.md'
    - Panejamento:
        - Planejamento da equipe:
          - 'Ferramentas': './planejamento/ferramentas.md'
          # 'Heatmap' : './planejamento/heatmap.md'
          # 'Metodologias' : './planejamento/metodologias.md'
          
        - Planejamento do projeto:
          - 'Cronograma': './planejamento/cronograma.md'
          - 'Processo de Design': './planejamento/processo.md'

        
        - 'Sites avaliados': './planejamento/sites.md'

theme:
  name: material
  logo: assets/channel.png
  favicon: assets/channel.png
  palette:
    primary: green
