site_name: Brasil Channel

nav:
    - Inicio: 'index.md'
    - Panejamento:
        - 'Ferramentas': './planejamento/ferramentas.md'
        - 'Cronograma': './planejamento/cronograma.md'
        - 'Sites avaliados': './planejamento/sites.md'
        - 'Processo de Design': './planejamento/processo.md'
    - Apresentações:
        - 'Apresentação 1': './apresentacoes/apresentacao1.md'

theme:
  name: material
  logo: assets/channel.png
  favicon: assets/channel.png
  palette:
    primary: green
