site_name: Brasil Channel

nav:
    - Inicio: 'index.md'
    - Sites_Avaliados:
        - 'Sites Avaliados': './docs/sites_avaliados/sites_avaliados.md'


nav:
    - Inicio: 'index.md'
    - Panejamento:
        - 'Ferramentas': './planejamento/ferramentas.md'

theme:
  name: material
