site_name: Brasil Channel

nav:
    - Inicio: 'index.md'
    - Panejamento:
        - Planejamento da equipe:
          - 'Ferramentas': './planejamento/ferramentas.md'
          
        - Planejamento do projeto:
          - 'Cronograma': './planejamento/cronograma.md'
          - 'Processo de Design': './planejamento/processo.md'
          - 'Sites avaliados': './planejamento/sites.md'

    - Apresentações:
        - 'Ponto de controle 1': './apresentacoes/apresentacao1.md'

theme:
  name: material
  logo: assets/channel.png
  favicon: assets/channel.png
  palette:
    primary: green
